kind: Secret
apiVersion: v1
metadata:
  name: drone-secret
  namespace: kubespark
type: Opaque
stringData:
  DRONE_GITHUB_CLIENT_ID: ???
  DRONE_GITHUB_CLIENT_SECRET: ???
  DRONE_RPC_SECRET: aKzfRGBgZVARtEIarLGHvicy1qjSe9zHXhivgcD3hcYktzbRC4pSGldyxhKa580d
  DRONE_SERVER_HOST: 172.31.0.88:30001
  DRONE_SERVER_PROTO: http
  DRONE_YAML_ENDPOINT: http://kubespark.kubespark.svc.cluster.local:8080/kapis/v1alpha1/drone/yaml
  DRONE_YAML_SECRET: aKzfRGBgZVARtEIarLGHvicy1qjSe9zHXhivgcD3hcYktzbRC4pSGldyxhKa580d
