kind: Secret
apiVersion: v1
metadata:
  name: drone-secret
  namespace: kubespark
type: Opaque
stringData:
  DRONE_GITHUB_CLIENT_ID: ???
  DRONE_GITHUB_CLIENT_SECRET: ???
  DRONE_RPC_SECRET: aKzfRGBgZVARtEIarLGHvicy1qjSe9zHXhivgcD3hcYktzbRC4pSGldyxhKa580d
  DRONE_SERVER_HOST: 172.31.0.88:30001
  DRONE_SERVER_PROTO: http
  DRONE_TOKEN: LXR7vxDRSXHLK7qUZOO4mHxEPhkMHddl
  DRONE_USER_CREATE: username:kubespark-bot,admin:true,machine:true,token:o16QIvXQYJqQVLlCEyYaoTsuODPbBI3VphGmMSXWDYEwqhRHvtZpMj3MFr7mbaUm
  DRONE_YAML_ENDPOINT: http://172.31.0.88:8080/kapis/v1alpha1/drone/yaml
  DRONE_YAML_SECRET: aKzfRGBgZVARtEIarLGHvicy1qjSe9zHXhivgcD3hcYktzbRC4pSGldyxhKa580d
