kind: Secret
apiVersion: v1
metadata:
  name: drone-secret
  namespace: kubespark
type: Opaque
stringData:
  DRONE_GITHUB_CLIENT_ID: test
  DRONE_GITHUB_CLIENT_SECRET: test
  DRONE_RPC_SECRET: aKzfRGBgZVARtEIarLGHvicy1qjSe9zHXhivgcD3hcYktzbRC4pSGldyxhKa580d
  DRONE_SERVER_HOST: 172.31.0.88:30001
  DRONE_SERVER_PROTO: http
