kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubespark-drone-server
  namespace: kubespark
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubespark-drone-server
  template:
    metadata:
      labels:
        app: kubespark-drone-server
        app.kubernetes.io/name: kubespark-drone-server
    spec:
      restartPolicy: Always
      containers:
        - name: drone
          image: drone/drone:2
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: DRONE_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_GITHUB_CLIENT_ID
            - name: DRONE_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_GITHUB_CLIENT_SECRET
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_RPC_SECRET
            - name: DRONE_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_SERVER_HOST
            - name: DRONE_SERVER_PROTO
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_SERVER_PROTO
            - name: DRONE_YAML_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_YAML_ENDPOINT
            - name: DRONE_YAML_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_YAML_SECRET
          ports:
            - name: tcp-80
              protocol: TCP
              containerPort: 80
          resources: {}
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: drone-data
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ""
        - name: drone-data
          persistentVolumeClaim:
            claimName: drone-data
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: kubespark-drone-server
  namespace: kubespark
spec:
  type: NodePort
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: kubespark-drone-server
  ports:
    - protocol: TCP
      name: tcp-80
      port: 80
      targetPort: 80
      nodePort: 30001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-data
  namespace: kubespark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeMode: Filesystem
