kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubespark-drone-runner
  namespace: kubespark
  annotations:
    deployment.kubernetes.io/revision: "11"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubespark-drone-runner
  template:
    metadata:
      labels:
        app: kubespark-drone-runner
        app.kubernetes.io/name: kubespark-drone-runner
    spec:
      restartPolicy: Always
      containers:
        - name: drone-runner-kube
          image: drone/drone-runner-kube:1.0.0-rc.5
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: DRONE_RUNNER_CAPACITY
              value: "2"
            - name: DRONE_RUNNER_NAME
              value: my-first-runner
            - name: DRONE_RPC_HOST
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_SERVER_HOST
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_RPC_SECRET
            - name: DRONE_RPC_PROTO
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_SERVER_PROTO
            - name: HTTP_PROXY
              value: http://172.31.0.1:7890
            - name: HTTPS_PROXY
              value: http://172.31.0.1:7890
            - name: NO_PROXY
              value: 127.0.0.1,localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local,kubernetes.default.svc,kubernetes.default
          resources: {}
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ""
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kubespark-admin
      serviceAccountName: kubespark-admin
      terminationGracePeriodSeconds: 30
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
