apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubespark-drone-runner
  namespace: kubespark
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubespark-drone-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubespark-drone-runner
        app: kubespark-drone-runner
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: default
      containers:
        - name: drone-runner-kube
          image: drone/drone-runner-kube:1.0.0-rc.5
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: DRONE_RUNNER_CAPACITY
              value: "2"
            - name: DRONE_RUNNER_NAME
              value: my-first-runner
            - name: DRONE_RPC_HOST
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_SERVER_HOST
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_RPC_SECRET
            - name: DRONE_RPC_PROTO
              valueFrom:
                secretKeyRef:
                  name: drone-secret
                  key: DRONE_SERVER_PROTO
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ""
  revisionHistoryLimit: 10
  replicas: 1
  progressDeadlineSeconds: 600
