apiVersion: v1
kind: Secret
metadata:
  name: kubespark-drone-yaml-secret
  namespace: kubespark
type: Opaque
stringData:
  kubespark: "kind: pipeline\r

    type: kubernetes\r

    name: docker-aliyun\r

    \r

    trigger:\r

    \  branch:\r

    \    - dev\r

    \  event:\r

    \    - push\r

    \    - custom\r

    \r

    steps:\r

    \  # =========================\r

    \  # 1️⃣ 构建验证\r

    \  # =========================\r

    \  - name: verify\r

    \    image: node:20\r

    \    commands:\r

    \      - npm ci\r

    \      - npm run lint\r

    \      - NODE_ENV=production npm run build\r

    \r

    \  # =========================\r

    \  # 2️⃣ 构建 + 推送阿里云镜像\r

    \  # =========================\r

    \  - name: docker\r

    \    image: plugins/docker\r

    \    settings:\r

    \      registry: registry.cn-hangzhou.aliyuncs.com   # 👈 阿里云\r

    \      repo: registry.cn-hangzhou.aliyuncs.com/tanqidi-temp/kubespark-console\r

    \      tags:\r

    \        - dev\r

    \      dockerfile: Dockerfile\r

    \      context: .\r

    \      platforms:\r

    \        - linux/amd64\r

    \        - linux/arm64\r

    \r

    \      username:\r

    \        from_secret: aliyun_username   # 👈 账号\r

    \      password:\r

    \        from_secret: aliyun_password   # 👈 密码\r

    \    depends_on:\r

    \      - verify\r

    \      \r\n"
