kind: Secret
apiVersion: v1
metadata:
  name: kubespark-secret
  namespace: kubespark
type: Opaque
stringData:
  DRONE_YAML_SECRET: aKzfRGBgZVARtEIarLGHvicy1qjSe9zHXhivgcD3hcYktzbRC4pSGldyxhKa580d
  KUBESPARK_JWT_SECRET: "*u/#a@6K9MOqHotx.B(WSSRiTl@V2q79o|2jAIs0fth-'4?K)ia[+#u85:Y}+u9]"
  KUBESPARK_PASSWORD: "123456"
  KUBESPARK_USERNAME: admin
