kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubespark-terminal
  namespace: kubespark
  annotations:
    description: 集群终端
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubespark-terminal
  template:
    metadata:
      labels:
        app: kubespark-terminal
        app.kubernetes.io/name: kubespark-terminal
    spec:
      restartPolicy: Always
      containers:
        - name: terminal
          image: alpine/k8s:1.34.4
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
          args:
            - -c
            - sleep infinity
          env:
            - name: TZ
              value: Asia/Shanghai
          resources: {}
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ""
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kubespark-admin
      serviceAccountName: kubespark-admin
      terminationGracePeriodSeconds: 30
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
