apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubespark-admin
  namespace: kubespark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubespark-admin
subjects:
  - kind: ServiceAccount
    name: kubespark-admin
    namespace: kubespark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
