export { WorkloadsPageClient } from "./workloads/workloads-page"
export { JobsPageClient } from "./jobs/jobs-page"
export { PodsPageClient } from "./pods/pods-page"
export { ServicesPageClient } from "./services/services-page"
export { RoutesPageClient } from "./routes/routes-page"
export { ConfigMapsPageClient } from "./configmaps/configmaps-page"
export { SecretsPageClient } from "./secrets/secrets-page"
export { VolumesPageClient } from "./volumes/volumes-page"
export { StorageClassesPageClient } from "./storageclasses/storageclasses-page"
export { NodesPageClient } from "./nodes/nodes-page"
export { ProjectsPageClient } from "./projects/projects-page"

