apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workspaces.tanqidi.com
  annotations:
    description: 企业空间资源
spec:
  group: tanqidi.com
  scope: Cluster
  names:
    plural: workspaces
    singular: workspace
    kind: Workspace
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                owner:
                  type: string
                  minLength: 1
                  maxLength: 128
              required:
                - owner
